### ISSUE TITLE
svsm will panic with one tpm2_createek command

### ISSUE THREAD

**Issue by liuw1** [gaojiaqi7/td-partitioning-svsm#6]
**Description:**
svsm will panic with tpm2_createek command "tpm2_createek --ek-context ecc_ek.ctx --key-algorithm ecc --public ecc_ek.pub"
version: commit 4700e32c8909a0aa2082abede745faabb8e81bb4

**Step:**
1. Launch tdp-svsm with TPM
2. Execute command "tpm2_createek --ek-context ecc_ek.ctx --key-algorithm ecc --public ecc_ek.pub"

**Expected:**
EK can be successfully created.

**Actual:**
```
tpm2_createek \tpm2_createek \
                --ek-context ecc_ek.ctx \
                --key-algorithm ecc \
                --public ecc_ek.pub
[SVSM] WARN: CRB_LOC_CTRL locality to write = 0 val = 1
[SVSM] WARN: CRB_LOC_CTRL locality to write = 0 val = 2
[SVSM] WARN: CRB_LOC_CTRL locality to write = 0 val = 1
[SVSM] WARN: CRB_LOC_CTRL locality to write = 0 val = 2
[SVSM] WARN: CRB_LOC_CTRL locality to write = 0 val = 1
[SVSM] WARN: CRB_LOC_CTRL locality to write = 0 val = 2
[SVSM] WARN: CRB_LOC_CTRL locality to write = 0 val = 1
[SVSM] ERROR: Panic: CPU[1] panicked at kernel/src/cpu/idt/svsm.rs:154:9:
Unhandled Page-Fault at RIP 0xffffff800004720c CR2: 0xffffff8010000000 error code: 0x0000000000000000
[SVSM] ---BACKTRACE---:
[SVSM]   [0xffffff8000003a9e]
[SVSM]   [0xffffff8000046f52]
[SVSM]   [0xffffff8000046fce]
[SVSM]   [0xffffff8000008bf2]
[SVSM]   [0xffffff8000049760]
[SVSM]   [0xffffff80000a1e9b]
[SVSM]   [0xffffff8000052af7]
[SVSM]   [0xffffff800000e665]
[SVSM]   [0xffffff8000004924]
[SVSM]   [0xffffff80001c24ca]
[SVSM]   [0xffffff8000214511]
[SVSM]   [0xffffff80001c4e73]
[SVSM]   [0xffffff800023e4b7]
[SVSM]   [0xffffff80002418d8]
[SVSM]   [0xffffff8000234cbc]
[SVSM]   [0xffffff8000237223]
[SVSM]   [0xffffff8000200ac1]
[SVSM]   [0xffffff80001b2e61]
[SVSM]   [0xffffff80001b3307]
[SVSM]   [0xffffff80001b37e9]
[SVSM]   [0xffffff8000130bc1]
[SVSM]   [0xffffff800016bef1]
[SVSM]   [0xffffff800016bec1]
[SVSM]   Invalid frame
[SVSM] ---END---
````

**Comment by gaojiaqi7** [comment]
From disassembly of the `svsm` binary, `red zone` for the stack frame is enabled. Take an openssl function that triggers the page fault as example, `%rsp` is not updated after entering the function `BN_ucmp`:

```
int BN_ucmp(const BIGNUM *a, const BIGNUM *b)
{
ffffff800002c0e5:	55                   	push   %rbp
ffffff800002c0e6:	48 89 e5             	mov    %rsp,%rbp
ffffff800002c0e9:	48 89 7d c8          	mov    %rdi,-0x38(%rbp)
ffffff800002c0ed:	48 89 75 c0          	mov    %rsi,-0x40(%rbp)
    BN_ULONG t1, t2, *ap, *bp;

    bn_check_top(a);
    bn_check_top(b);

    i = a->top - b->top;
ffffff800002c0f1:	48 8b 45 c8          	mov    -0x38(%rbp),%rax
ffffff800002c0f5:	8b 50 08             	mov    0x8(%rax),%edx
ffffff800002c0f8:	48 8b 45 c0          	mov    -0x40(%rbp),%rax
ffffff800002c0fc:	8b 48 08             	mov    0x8(%rax),%ecx
ffffff800002c0ff:	89 d0                	mov    %edx,%eax
ffffff800002c101:	29 c8                	sub    %ecx,%eax
ffffff800002c103:	89 45 fc             	mov    %eax,-0x4(%rbp)
    if (i != 0)
ffffff800002c106:	83 7d fc 00          	cmpl   $0x0,-0x4(%rbp)
ffffff800002c10a:	74 08                	je     ffffff800002c114 <BN_ucmp+0x2f>
        return i;
ffffff800002c10c:	8b 45 fc             	mov    -0x4(%rbp),%eax
ffffff800002c10f:	e9 8c 00 00 00       	jmp    ffffff800002c1a0 <BN_ucmp+0xbb>
    ap = a->d;
ffffff800002c114:	48 8b 45 c8          	mov    -0x38(%rbp),%rax
ffffff800002c118:	48 8b 00             	mov    (%rax),%rax
ffffff800002c11b:	48 89 45 f0          	mov    %rax,-0x10(%rbp)
    bp = b->d;
ffffff800002c11f:	48 8b 45 c0          	mov    -0x40(%rbp),%rax
ffffff800002c123:	48 8b 00             	mov    (%rax),%rax
ffffff800002c126:	48 89 45 e8          	mov    %rax,-0x18(%rbp)
```

When a interrupt is triggered, CPU pushes values of registers such as SS, RSP and RIP into the stack and the interrupt handler under the current implementation does not aware the `red zone`, so after returning back from interrupt, stack is corrupted and exception occurs.

There might be two solutions for this issue:

 - 1. Use interrupt stack for interrupt and exceptions

Set the interrupt stack address in TSS and specify the stack index in the target IDT entry. When interrupt is comming, CPU will switch to the standalone stack automatically.

Implementation: https://github.com/gaojiaqi7/td-partitioning-svsm/commit/156315082a026af110cdcd54dce8648ad85ca158

 - 2. Set `-mno-red-zone` CFLAGS for external C libraries.

See https://gcc.gnu.org/onlinedocs/gcc-8.5.0/gcc/x86-Options.html

Implementation: https://github.com/gaojiaqi7/td-partitioning-svsm/commit/8fc5f1833b579018c7010f229027b1b98faa2895

**Comment by gaojiaqi7** [comment]
From System V x86_64 ABI spec: 

3.2.2 The Stack Frame

The 128-byte area beyond the location pointed to by %rsp is considered to
be reserved and shall not be modified by signal or interrupt handlers.8 Therefore,
functions may use this area for temporary data that is not needed across function
calls. In particular, leaf functions may use this area for their entire stack frame,
rather than adjusting the stack pointer in the prologue and epilogue. This area is
known as the red zone

A.2.2 Stack Layout

The Linux kernel does not honor the red zone (see 3.2.2 and therefore this area is
not allowed to be used by kernel code. Kernel code should be compiled by GCC
with the option -mno-red-zone

**Comment by gaojiaqi7** [comment]
For rust `x86_64-unknown-none` target, red zone is disabled by default: https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/targets/x86_64_unknown_none.rs#L25C9-L25C24

**Comment by gaojiaqi7** [comment]
Closed with https://github.com/intel-staging/td-partitioning-svsm/commit/a39d666ccc61a3f81e3c16e7454a296f4f9a111f
